<?php
/**
 * includes/countries_data.php — Comprehensive Country & State Data (PR #17)
 *
 * Provides:
 *   - 240+ countries with code, name, phone_code, flag emoji, postal_regex, has_states
 *   - States/provinces for US, CA, AU, IN, UK, BD, DE, FR, CN, JP
 *   - Postal code regex patterns per country
 *   - Phone number format data per country
 */

/**
 * Return the full countries array.
 * Each entry: code, name, phone_code, flag, postal_regex, has_states
 */
function getCountriesData(): array
{
    static $data = null;
    if ($data !== null) return $data;

    $data = [
        ['code'=>'AF','name'=>'Afghanistan',                'phone_code'=>'+93',  'flag'=>'🇦🇫','postal_regex'=>'/^\d{4}$/','has_states'=>false],
        ['code'=>'AL','name'=>'Albania',                    'phone_code'=>'+355', 'flag'=>'🇦🇱','postal_regex'=>'/^\d{4}$/','has_states'=>false],
        ['code'=>'DZ','name'=>'Algeria',                    'phone_code'=>'+213', 'flag'=>'🇩🇿','postal_regex'=>'/^\d{5}$/','has_states'=>false],
        ['code'=>'AD','name'=>'Andorra',                    'phone_code'=>'+376', 'flag'=>'🇦🇩','postal_regex'=>'/^AD\d{3}$/i','has_states'=>false],
        ['code'=>'AO','name'=>'Angola',                     'phone_code'=>'+244', 'flag'=>'🇦🇴','postal_regex'=>'','has_states'=>false],
        ['code'=>'AG','name'=>'Antigua and Barbuda',        'phone_code'=>'+1',   'flag'=>'🇦🇬','postal_regex'=>'','has_states'=>false],
        ['code'=>'AR','name'=>'Argentina',                  'phone_code'=>'+54',  'flag'=>'🇦🇷','postal_regex'=>'/^[A-Z]\d{4}[A-Z]{3}$/i','has_states'=>false],
        ['code'=>'AM','name'=>'Armenia',                    'phone_code'=>'+374', 'flag'=>'🇦🇲','postal_regex'=>'/^\d{4}$/','has_states'=>false],
        ['code'=>'AU','name'=>'Australia',                  'phone_code'=>'+61',  'flag'=>'🇦🇺','postal_regex'=>'/^\d{4}$/','has_states'=>true],
        ['code'=>'AT','name'=>'Austria',                    'phone_code'=>'+43',  'flag'=>'🇦🇹','postal_regex'=>'/^\d{4}$/','has_states'=>false],
        ['code'=>'AZ','name'=>'Azerbaijan',                 'phone_code'=>'+994', 'flag'=>'🇦🇿','postal_regex'=>'/^AZ\d{4}$/i','has_states'=>false],
        ['code'=>'BS','name'=>'Bahamas',                    'phone_code'=>'+1',   'flag'=>'🇧🇸','postal_regex'=>'','has_states'=>false],
        ['code'=>'BH','name'=>'Bahrain',                    'phone_code'=>'+973', 'flag'=>'🇧🇭','postal_regex'=>'/^\d{3,4}$/','has_states'=>false],
        ['code'=>'BD','name'=>'Bangladesh',                 'phone_code'=>'+880', 'flag'=>'🇧🇩','postal_regex'=>'/^\d{4}$/','has_states'=>true],
        ['code'=>'BB','name'=>'Barbados',                   'phone_code'=>'+1',   'flag'=>'🇧🇧','postal_regex'=>'/^BB\d{5}$/i','has_states'=>false],
        ['code'=>'BY','name'=>'Belarus',                    'phone_code'=>'+375', 'flag'=>'🇧🇾','postal_regex'=>'/^\d{6}$/','has_states'=>false],
        ['code'=>'BE','name'=>'Belgium',                    'phone_code'=>'+32',  'flag'=>'🇧🇪','postal_regex'=>'/^\d{4}$/','has_states'=>false],
        ['code'=>'BZ','name'=>'Belize',                     'phone_code'=>'+501', 'flag'=>'🇧🇿','postal_regex'=>'','has_states'=>false],
        ['code'=>'BJ','name'=>'Benin',                      'phone_code'=>'+229', 'flag'=>'🇧🇯','postal_regex'=>'','has_states'=>false],
        ['code'=>'BT','name'=>'Bhutan',                     'phone_code'=>'+975', 'flag'=>'🇧🇹','postal_regex'=>'/^\d{5}$/','has_states'=>false],
        ['code'=>'BO','name'=>'Bolivia',                    'phone_code'=>'+591', 'flag'=>'🇧🇴','postal_regex'=>'','has_states'=>false],
        ['code'=>'BA','name'=>'Bosnia and Herzegovina',     'phone_code'=>'+387', 'flag'=>'🇧🇦','postal_regex'=>'/^\d{5}$/','has_states'=>false],
        ['code'=>'BW','name'=>'Botswana',                   'phone_code'=>'+267', 'flag'=>'🇧🇼','postal_regex'=>'','has_states'=>false],
        ['code'=>'BR','name'=>'Brazil',                     'phone_code'=>'+55',  'flag'=>'🇧🇷','postal_regex'=>'/^\d{5}-?\d{3}$/','has_states'=>false],
        ['code'=>'BN','name'=>'Brunei',                     'phone_code'=>'+673', 'flag'=>'🇧🇳','postal_regex'=>'/^[A-Z]{2}\d{4}$/i','has_states'=>false],
        ['code'=>'BG','name'=>'Bulgaria',                   'phone_code'=>'+359', 'flag'=>'🇧🇬','postal_regex'=>'/^\d{4}$/','has_states'=>false],
        ['code'=>'BF','name'=>'Burkina Faso',               'phone_code'=>'+226', 'flag'=>'🇧🇫','postal_regex'=>'','has_states'=>false],
        ['code'=>'BI','name'=>'Burundi',                    'phone_code'=>'+257', 'flag'=>'🇧🇮','postal_regex'=>'','has_states'=>false],
        ['code'=>'CV','name'=>'Cabo Verde',                 'phone_code'=>'+238', 'flag'=>'🇨🇻','postal_regex'=>'/^\d{4}$/','has_states'=>false],
        ['code'=>'KH','name'=>'Cambodia',                   'phone_code'=>'+855', 'flag'=>'🇰🇭','postal_regex'=>'/^\d{5,6}$/','has_states'=>false],
        ['code'=>'CM','name'=>'Cameroon',                   'phone_code'=>'+237', 'flag'=>'🇨🇲','postal_regex'=>'','has_states'=>false],
        ['code'=>'CA','name'=>'Canada',                     'phone_code'=>'+1',   'flag'=>'🇨🇦','postal_regex'=>'/^[ABCEGHJ-NPRSTVXY]\d[ABCEGHJ-NPRSTV-Z]\s?\d[ABCEGHJ-NPRSTV-Z]\d$/i','has_states'=>true],
        ['code'=>'CF','name'=>'Central African Republic',   'phone_code'=>'+236', 'flag'=>'🇨🇫','postal_regex'=>'','has_states'=>false],
        ['code'=>'TD','name'=>'Chad',                       'phone_code'=>'+235', 'flag'=>'🇹🇩','postal_regex'=>'','has_states'=>false],
        ['code'=>'CL','name'=>'Chile',                      'phone_code'=>'+56',  'flag'=>'🇨🇱','postal_regex'=>'/^\d{7}$/','has_states'=>false],
        ['code'=>'CN','name'=>'China',                      'phone_code'=>'+86',  'flag'=>'🇨🇳','postal_regex'=>'/^\d{6}$/','has_states'=>true],
        ['code'=>'CO','name'=>'Colombia',                   'phone_code'=>'+57',  'flag'=>'🇨🇴','postal_regex'=>'/^\d{6}$/','has_states'=>false],
        ['code'=>'KM','name'=>'Comoros',                    'phone_code'=>'+269', 'flag'=>'🇰🇲','postal_regex'=>'','has_states'=>false],
        ['code'=>'CD','name'=>'Congo (DRC)',                'phone_code'=>'+243', 'flag'=>'🇨🇩','postal_regex'=>'','has_states'=>false],
        ['code'=>'CG','name'=>'Congo (Republic)',           'phone_code'=>'+242', 'flag'=>'🇨🇬','postal_regex'=>'','has_states'=>false],
        ['code'=>'CR','name'=>'Costa Rica',                 'phone_code'=>'+506', 'flag'=>'🇨🇷','postal_regex'=>'/^\d{5}$/','has_states'=>false],
        ['code'=>'CI','name'=>'Côte d\'Ivoire',            'phone_code'=>'+225', 'flag'=>'🇨🇮','postal_regex'=>'','has_states'=>false],
        ['code'=>'HR','name'=>'Croatia',                    'phone_code'=>'+385', 'flag'=>'🇭🇷','postal_regex'=>'/^\d{5}$/','has_states'=>false],
        ['code'=>'CU','name'=>'Cuba',                       'phone_code'=>'+53',  'flag'=>'🇨🇺','postal_regex'=>'/^\d{5}$/','has_states'=>false],
        ['code'=>'CY','name'=>'Cyprus',                     'phone_code'=>'+357', 'flag'=>'🇨🇾','postal_regex'=>'/^\d{4}$/','has_states'=>false],
        ['code'=>'CZ','name'=>'Czech Republic',             'phone_code'=>'+420', 'flag'=>'🇨🇿','postal_regex'=>'/^\d{3}\s?\d{2}$/','has_states'=>false],
        ['code'=>'DK','name'=>'Denmark',                    'phone_code'=>'+45',  'flag'=>'🇩🇰','postal_regex'=>'/^\d{4}$/','has_states'=>false],
        ['code'=>'DJ','name'=>'Djibouti',                   'phone_code'=>'+253', 'flag'=>'🇩🇯','postal_regex'=>'','has_states'=>false],
        ['code'=>'DM','name'=>'Dominica',                   'phone_code'=>'+1',   'flag'=>'🇩🇲','postal_regex'=>'','has_states'=>false],
        ['code'=>'DO','name'=>'Dominican Republic',         'phone_code'=>'+1',   'flag'=>'🇩🇴','postal_regex'=>'/^\d{5}$/','has_states'=>false],
        ['code'=>'EC','name'=>'Ecuador',                    'phone_code'=>'+593', 'flag'=>'🇪🇨','postal_regex'=>'/^\d{6}$/','has_states'=>false],
        ['code'=>'EG','name'=>'Egypt',                      'phone_code'=>'+20',  'flag'=>'🇪🇬','postal_regex'=>'/^\d{5}$/','has_states'=>false],
        ['code'=>'SV','name'=>'El Salvador',                'phone_code'=>'+503', 'flag'=>'🇸🇻','postal_regex'=>'/^\d{4}$/','has_states'=>false],
        ['code'=>'GQ','name'=>'Equatorial Guinea',          'phone_code'=>'+240', 'flag'=>'🇬🇶','postal_regex'=>'','has_states'=>false],
        ['code'=>'ER','name'=>'Eritrea',                    'phone_code'=>'+291', 'flag'=>'🇪🇷','postal_regex'=>'','has_states'=>false],
        ['code'=>'EE','name'=>'Estonia',                    'phone_code'=>'+372', 'flag'=>'🇪🇪','postal_regex'=>'/^\d{5}$/','has_states'=>false],
        ['code'=>'SZ','name'=>'Eswatini',                   'phone_code'=>'+268', 'flag'=>'🇸🇿','postal_regex'=>'/^[A-Z]\d{3}$/i','has_states'=>false],
        ['code'=>'ET','name'=>'Ethiopia',                   'phone_code'=>'+251', 'flag'=>'🇪🇹','postal_regex'=>'/^\d{4}$/','has_states'=>false],
        ['code'=>'FJ','name'=>'Fiji',                       'phone_code'=>'+679', 'flag'=>'🇫🇯','postal_regex'=>'','has_states'=>false],
        ['code'=>'FI','name'=>'Finland',                    'phone_code'=>'+358', 'flag'=>'🇫🇮','postal_regex'=>'/^\d{5}$/','has_states'=>false],
        ['code'=>'FR','name'=>'France',                     'phone_code'=>'+33',  'flag'=>'🇫🇷','postal_regex'=>'/^\d{5}$/','has_states'=>true],
        ['code'=>'GA','name'=>'Gabon',                      'phone_code'=>'+241', 'flag'=>'🇬🇦','postal_regex'=>'','has_states'=>false],
        ['code'=>'GM','name'=>'Gambia',                     'phone_code'=>'+220', 'flag'=>'🇬🇲','postal_regex'=>'','has_states'=>false],
        ['code'=>'GE','name'=>'Georgia',                    'phone_code'=>'+995', 'flag'=>'🇬🇪','postal_regex'=>'/^\d{4}$/','has_states'=>false],
        ['code'=>'DE','name'=>'Germany',                    'phone_code'=>'+49',  'flag'=>'🇩🇪','postal_regex'=>'/^\d{5}$/','has_states'=>true],
        ['code'=>'GH','name'=>'Ghana',                      'phone_code'=>'+233', 'flag'=>'🇬🇭','postal_regex'=>'','has_states'=>false],
        ['code'=>'GR','name'=>'Greece',                     'phone_code'=>'+30',  'flag'=>'🇬🇷','postal_regex'=>'/^\d{3}\s?\d{2}$/','has_states'=>false],
        ['code'=>'GD','name'=>'Grenada',                    'phone_code'=>'+1',   'flag'=>'🇬🇩','postal_regex'=>'','has_states'=>false],
        ['code'=>'GT','name'=>'Guatemala',                  'phone_code'=>'+502', 'flag'=>'🇬🇹','postal_regex'=>'/^\d{5}$/','has_states'=>false],
        ['code'=>'GN','name'=>'Guinea',                     'phone_code'=>'+224', 'flag'=>'🇬🇳','postal_regex'=>'','has_states'=>false],
        ['code'=>'GW','name'=>'Guinea-Bissau',              'phone_code'=>'+245', 'flag'=>'🇬🇼','postal_regex'=>'/^\d{4}$/','has_states'=>false],
        ['code'=>'GY','name'=>'Guyana',                     'phone_code'=>'+592', 'flag'=>'🇬🇾','postal_regex'=>'','has_states'=>false],
        ['code'=>'HT','name'=>'Haiti',                      'phone_code'=>'+509', 'flag'=>'🇭🇹','postal_regex'=>'/^HT\d{4}$/i','has_states'=>false],
        ['code'=>'HN','name'=>'Honduras',                   'phone_code'=>'+504', 'flag'=>'🇭🇳','postal_regex'=>'/^\d{5}$/','has_states'=>false],
        ['code'=>'HK','name'=>'Hong Kong',                  'phone_code'=>'+852', 'flag'=>'🇭🇰','postal_regex'=>'','has_states'=>false],
        ['code'=>'HU','name'=>'Hungary',                    'phone_code'=>'+36',  'flag'=>'🇭🇺','postal_regex'=>'/^\d{4}$/','has_states'=>false],
        ['code'=>'IS','name'=>'Iceland',                    'phone_code'=>'+354', 'flag'=>'🇮🇸','postal_regex'=>'/^\d{3}$/','has_states'=>false],
        ['code'=>'IN','name'=>'India',                      'phone_code'=>'+91',  'flag'=>'🇮🇳','postal_regex'=>'/^\d{6}$/','has_states'=>true],
        ['code'=>'ID','name'=>'Indonesia',                  'phone_code'=>'+62',  'flag'=>'🇮🇩','postal_regex'=>'/^\d{5}$/','has_states'=>false],
        ['code'=>'IR','name'=>'Iran',                       'phone_code'=>'+98',  'flag'=>'🇮🇷','postal_regex'=>'/^\d{10}$/','has_states'=>false],
        ['code'=>'IQ','name'=>'Iraq',                       'phone_code'=>'+964', 'flag'=>'🇮🇶','postal_regex'=>'/^\d{5}$/','has_states'=>false],
        ['code'=>'IE','name'=>'Ireland',                    'phone_code'=>'+353', 'flag'=>'🇮🇪','postal_regex'=>'/^[AC-FHKNPRTV-Y]\d{2}[W-Y0-9]\s?[0-9AC-FHKNPRTV-Y]{4}$/i','has_states'=>false],
        ['code'=>'IL','name'=>'Israel',                     'phone_code'=>'+972', 'flag'=>'🇮🇱','postal_regex'=>'/^\d{7}$/','has_states'=>false],
        ['code'=>'IT','name'=>'Italy',                      'phone_code'=>'+39',  'flag'=>'🇮🇹','postal_regex'=>'/^\d{5}$/','has_states'=>false],
        ['code'=>'JM','name'=>'Jamaica',                    'phone_code'=>'+1',   'flag'=>'🇯🇲','postal_regex'=>'/^JM[A-Z]{3}\d{2}$/i','has_states'=>false],
        ['code'=>'JP','name'=>'Japan',                      'phone_code'=>'+81',  'flag'=>'🇯🇵','postal_regex'=>'/^\d{3}-?\d{4}$/','has_states'=>true],
        ['code'=>'JO','name'=>'Jordan',                     'phone_code'=>'+962', 'flag'=>'🇯🇴','postal_regex'=>'/^\d{5}$/','has_states'=>false],
        ['code'=>'KZ','name'=>'Kazakhstan',                 'phone_code'=>'+7',   'flag'=>'🇰🇿','postal_regex'=>'/^\d{6}$/','has_states'=>false],
        ['code'=>'KE','name'=>'Kenya',                      'phone_code'=>'+254', 'flag'=>'🇰🇪','postal_regex'=>'/^\d{5}$/','has_states'=>false],
        ['code'=>'KI','name'=>'Kiribati',                   'phone_code'=>'+686', 'flag'=>'🇰🇮','postal_regex'=>'','has_states'=>false],
        ['code'=>'KP','name'=>'North Korea',                'phone_code'=>'+850', 'flag'=>'🇰🇵','postal_regex'=>'','has_states'=>false],
        ['code'=>'KR','name'=>'South Korea',                'phone_code'=>'+82',  'flag'=>'🇰🇷','postal_regex'=>'/^\d{5}$/','has_states'=>false],
        ['code'=>'KW','name'=>'Kuwait',                     'phone_code'=>'+965', 'flag'=>'🇰🇼','postal_regex'=>'/^\d{5}$/','has_states'=>false],
        ['code'=>'KG','name'=>'Kyrgyzstan',                 'phone_code'=>'+996', 'flag'=>'🇰🇬','postal_regex'=>'/^\d{6}$/','has_states'=>false],
        ['code'=>'LA','name'=>'Laos',                       'phone_code'=>'+856', 'flag'=>'🇱🇦','postal_regex'=>'/^\d{5}$/','has_states'=>false],
        ['code'=>'LV','name'=>'Latvia',                     'phone_code'=>'+371', 'flag'=>'🇱🇻','postal_regex'=>'/^LV-\d{4}$/i','has_states'=>false],
        ['code'=>'LB','name'=>'Lebanon',                    'phone_code'=>'+961', 'flag'=>'🇱🇧','postal_regex'=>'/^\d{4,5}$/','has_states'=>false],
        ['code'=>'LS','name'=>'Lesotho',                    'phone_code'=>'+266', 'flag'=>'🇱🇸','postal_regex'=>'/^\d{3}$/','has_states'=>false],
        ['code'=>'LR','name'=>'Liberia',                    'phone_code'=>'+231', 'flag'=>'🇱🇷','postal_regex'=>'/^\d{4}$/','has_states'=>false],
        ['code'=>'LY','name'=>'Libya',                      'phone_code'=>'+218', 'flag'=>'🇱🇾','postal_regex'=>'','has_states'=>false],
        ['code'=>'LI','name'=>'Liechtenstein',              'phone_code'=>'+423', 'flag'=>'🇱🇮','postal_regex'=>'/^\d{4}$/','has_states'=>false],
        ['code'=>'LT','name'=>'Lithuania',                  'phone_code'=>'+370', 'flag'=>'🇱🇹','postal_regex'=>'/^LT-\d{5}$/i','has_states'=>false],
        ['code'=>'LU','name'=>'Luxembourg',                 'phone_code'=>'+352', 'flag'=>'🇱🇺','postal_regex'=>'/^\d{4}$/','has_states'=>false],
        ['code'=>'MO','name'=>'Macao',                      'phone_code'=>'+853', 'flag'=>'🇲🇴','postal_regex'=>'','has_states'=>false],
        ['code'=>'MG','name'=>'Madagascar',                 'phone_code'=>'+261', 'flag'=>'🇲🇬','postal_regex'=>'/^\d{3}$/','has_states'=>false],
        ['code'=>'MW','name'=>'Malawi',                     'phone_code'=>'+265', 'flag'=>'🇲🇼','postal_regex'=>'','has_states'=>false],
        ['code'=>'MY','name'=>'Malaysia',                   'phone_code'=>'+60',  'flag'=>'🇲🇾','postal_regex'=>'/^\d{5}$/','has_states'=>false],
        ['code'=>'MV','name'=>'Maldives',                   'phone_code'=>'+960', 'flag'=>'🇲🇻','postal_regex'=>'/^\d{5}$/','has_states'=>false],
        ['code'=>'ML','name'=>'Mali',                       'phone_code'=>'+223', 'flag'=>'🇲🇱','postal_regex'=>'','has_states'=>false],
        ['code'=>'MT','name'=>'Malta',                      'phone_code'=>'+356', 'flag'=>'🇲🇹','postal_regex'=>'/^[A-Z]{3}\s?\d{4}$/i','has_states'=>false],
        ['code'=>'MH','name'=>'Marshall Islands',           'phone_code'=>'+692', 'flag'=>'🇲🇭','postal_regex'=>'/^\d{5}(-\d{4})?$/','has_states'=>false],
        ['code'=>'MR','name'=>'Mauritania',                 'phone_code'=>'+222', 'flag'=>'🇲🇷','postal_regex'=>'','has_states'=>false],
        ['code'=>'MU','name'=>'Mauritius',                  'phone_code'=>'+230', 'flag'=>'🇲🇺','postal_regex'=>'/^\d{5}$/','has_states'=>false],
        ['code'=>'MX','name'=>'Mexico',                     'phone_code'=>'+52',  'flag'=>'🇲🇽','postal_regex'=>'/^\d{5}$/','has_states'=>false],
        ['code'=>'FM','name'=>'Micronesia',                 'phone_code'=>'+691', 'flag'=>'🇫🇲','postal_regex'=>'/^\d{5}(-\d{4})?$/','has_states'=>false],
        ['code'=>'MD','name'=>'Moldova',                    'phone_code'=>'+373', 'flag'=>'🇲🇩','postal_regex'=>'/^MD-\d{4}$/i','has_states'=>false],
        ['code'=>'MC','name'=>'Monaco',                     'phone_code'=>'+377', 'flag'=>'🇲🇨','postal_regex'=>'/^980\d{2}$/','has_states'=>false],
        ['code'=>'MN','name'=>'Mongolia',                   'phone_code'=>'+976', 'flag'=>'🇲🇳','postal_regex'=>'/^\d{5}$/','has_states'=>false],
        ['code'=>'ME','name'=>'Montenegro',                 'phone_code'=>'+382', 'flag'=>'🇲🇪','postal_regex'=>'/^\d{5}$/','has_states'=>false],
        ['code'=>'MA','name'=>'Morocco',                    'phone_code'=>'+212', 'flag'=>'🇲🇦','postal_regex'=>'/^\d{5}$/','has_states'=>false],
        ['code'=>'MZ','name'=>'Mozambique',                 'phone_code'=>'+258', 'flag'=>'🇲🇿','postal_regex'=>'/^\d{4}$/','has_states'=>false],
        ['code'=>'MM','name'=>'Myanmar',                    'phone_code'=>'+95',  'flag'=>'🇲🇲','postal_regex'=>'/^\d{5}$/','has_states'=>false],
        ['code'=>'NA','name'=>'Namibia',                    'phone_code'=>'+264', 'flag'=>'🇳🇦','postal_regex'=>'','has_states'=>false],
        ['code'=>'NR','name'=>'Nauru',                      'phone_code'=>'+674', 'flag'=>'🇳🇷','postal_regex'=>'','has_states'=>false],
        ['code'=>'NP','name'=>'Nepal',                      'phone_code'=>'+977', 'flag'=>'🇳🇵','postal_regex'=>'/^\d{5}$/','has_states'=>false],
        ['code'=>'NL','name'=>'Netherlands',                'phone_code'=>'+31',  'flag'=>'🇳🇱','postal_regex'=>'/^\d{4}\s?[A-Z]{2}$/i','has_states'=>false],
        ['code'=>'NZ','name'=>'New Zealand',                'phone_code'=>'+64',  'flag'=>'🇳🇿','postal_regex'=>'/^\d{4}$/','has_states'=>false],
        ['code'=>'NI','name'=>'Nicaragua',                  'phone_code'=>'+505', 'flag'=>'🇳🇮','postal_regex'=>'/^\d{5}$/','has_states'=>false],
        ['code'=>'NE','name'=>'Niger',                      'phone_code'=>'+227', 'flag'=>'🇳🇪','postal_regex'=>'/^\d{4}$/','has_states'=>false],
        ['code'=>'NG','name'=>'Nigeria',                    'phone_code'=>'+234', 'flag'=>'🇳🇬','postal_regex'=>'/^\d{6}$/','has_states'=>false],
        ['code'=>'MK','name'=>'North Macedonia',            'phone_code'=>'+389', 'flag'=>'🇲🇰','postal_regex'=>'/^\d{4}$/','has_states'=>false],
        ['code'=>'NO','name'=>'Norway',                     'phone_code'=>'+47',  'flag'=>'🇳🇴','postal_regex'=>'/^\d{4}$/','has_states'=>false],
        ['code'=>'OM','name'=>'Oman',                       'phone_code'=>'+968', 'flag'=>'🇴🇲','postal_regex'=>'/^\d{3}$/','has_states'=>false],
        ['code'=>'PK','name'=>'Pakistan',                   'phone_code'=>'+92',  'flag'=>'🇵🇰','postal_regex'=>'/^\d{5}$/','has_states'=>false],
        ['code'=>'PW','name'=>'Palau',                      'phone_code'=>'+680', 'flag'=>'🇵🇼','postal_regex'=>'/^\d{5}$/','has_states'=>false],
        ['code'=>'PA','name'=>'Panama',                     'phone_code'=>'+507', 'flag'=>'🇵🇦','postal_regex'=>'/^\d{4}$/','has_states'=>false],
        ['code'=>'PG','name'=>'Papua New Guinea',           'phone_code'=>'+675', 'flag'=>'🇵🇬','postal_regex'=>'/^\d{3}$/','has_states'=>false],
        ['code'=>'PY','name'=>'Paraguay',                   'phone_code'=>'+595', 'flag'=>'🇵🇾','postal_regex'=>'/^\d{4}$/','has_states'=>false],
        ['code'=>'PE','name'=>'Peru',                       'phone_code'=>'+51',  'flag'=>'🇵🇪','postal_regex'=>'/^(0[1-9]|[12]\d|[3][0-4])\d{3}$/','has_states'=>false],
        ['code'=>'PH','name'=>'Philippines',                'phone_code'=>'+63',  'flag'=>'🇵🇭','postal_regex'=>'/^\d{4}$/','has_states'=>false],
        ['code'=>'PL','name'=>'Poland',                     'phone_code'=>'+48',  'flag'=>'🇵🇱','postal_regex'=>'/^\d{2}-\d{3}$/','has_states'=>false],
        ['code'=>'PT','name'=>'Portugal',                   'phone_code'=>'+351', 'flag'=>'🇵🇹','postal_regex'=>'/^\d{4}-\d{3}$/','has_states'=>false],
        ['code'=>'QA','name'=>'Qatar',                      'phone_code'=>'+974', 'flag'=>'🇶🇦','postal_regex'=>'','has_states'=>false],
        ['code'=>'RO','name'=>'Romania',                    'phone_code'=>'+40',  'flag'=>'🇷🇴','postal_regex'=>'/^\d{6}$/','has_states'=>false],
        ['code'=>'RU','name'=>'Russia',                     'phone_code'=>'+7',   'flag'=>'🇷🇺','postal_regex'=>'/^\d{6}$/','has_states'=>false],
        ['code'=>'RW','name'=>'Rwanda',                     'phone_code'=>'+250', 'flag'=>'🇷🇼','postal_regex'=>'','has_states'=>false],
        ['code'=>'KN','name'=>'Saint Kitts and Nevis',      'phone_code'=>'+1',   'flag'=>'🇰🇳','postal_regex'=>'','has_states'=>false],
        ['code'=>'LC','name'=>'Saint Lucia',                'phone_code'=>'+1',   'flag'=>'🇱🇨','postal_regex'=>'','has_states'=>false],
        ['code'=>'VC','name'=>'Saint Vincent and the Grenadines','phone_code'=>'+1','flag'=>'🇻🇨','postal_regex'=>'/^VC\d{4}$/i','has_states'=>false],
        ['code'=>'WS','name'=>'Samoa',                      'phone_code'=>'+685', 'flag'=>'🇼🇸','postal_regex'=>'','has_states'=>false],
        ['code'=>'SM','name'=>'San Marino',                 'phone_code'=>'+378', 'flag'=>'🇸🇲','postal_regex'=>'/^4789\d$/','has_states'=>false],
        ['code'=>'ST','name'=>'Sao Tome and Principe',      'phone_code'=>'+239', 'flag'=>'🇸🇹','postal_regex'=>'','has_states'=>false],
        ['code'=>'SA','name'=>'Saudi Arabia',               'phone_code'=>'+966', 'flag'=>'🇸🇦','postal_regex'=>'/^\d{5}(-\d{4})?$/','has_states'=>false],
        ['code'=>'SN','name'=>'Senegal',                    'phone_code'=>'+221', 'flag'=>'🇸🇳','postal_regex'=>'/^\d{5}$/','has_states'=>false],
        ['code'=>'RS','name'=>'Serbia',                     'phone_code'=>'+381', 'flag'=>'🇷🇸','postal_regex'=>'/^\d{5}$/','has_states'=>false],
        ['code'=>'SC','name'=>'Seychelles',                 'phone_code'=>'+248', 'flag'=>'🇸🇨','postal_regex'=>'','has_states'=>false],
        ['code'=>'SL','name'=>'Sierra Leone',               'phone_code'=>'+232', 'flag'=>'🇸🇱','postal_regex'=>'','has_states'=>false],
        ['code'=>'SG','name'=>'Singapore',                  'phone_code'=>'+65',  'flag'=>'🇸🇬','postal_regex'=>'/^\d{6}$/','has_states'=>false],
        ['code'=>'SK','name'=>'Slovakia',                   'phone_code'=>'+421', 'flag'=>'🇸🇰','postal_regex'=>'/^\d{3}\s?\d{2}$/','has_states'=>false],
        ['code'=>'SI','name'=>'Slovenia',                   'phone_code'=>'+386', 'flag'=>'🇸🇮','postal_regex'=>'/^\d{4}$/','has_states'=>false],
        ['code'=>'SB','name'=>'Solomon Islands',            'phone_code'=>'+677', 'flag'=>'🇸🇧','postal_regex'=>'','has_states'=>false],
        ['code'=>'SO','name'=>'Somalia',                    'phone_code'=>'+252', 'flag'=>'🇸🇴','postal_regex'=>'','has_states'=>false],
        ['code'=>'ZA','name'=>'South Africa',               'phone_code'=>'+27',  'flag'=>'🇿🇦','postal_regex'=>'/^\d{4}$/','has_states'=>false],
        ['code'=>'SS','name'=>'South Sudan',                'phone_code'=>'+211', 'flag'=>'🇸🇸','postal_regex'=>'','has_states'=>false],
        ['code'=>'ES','name'=>'Spain',                      'phone_code'=>'+34',  'flag'=>'🇪🇸','postal_regex'=>'/^\d{5}$/','has_states'=>false],
        ['code'=>'LK','name'=>'Sri Lanka',                  'phone_code'=>'+94',  'flag'=>'🇱🇰','postal_regex'=>'/^\d{5}$/','has_states'=>false],
        ['code'=>'SD','name'=>'Sudan',                      'phone_code'=>'+249', 'flag'=>'🇸🇩','postal_regex'=>'/^\d{5}$/','has_states'=>false],
        ['code'=>'SR','name'=>'Suriname',                   'phone_code'=>'+597', 'flag'=>'🇸🇷','postal_regex'=>'','has_states'=>false],
        ['code'=>'SE','name'=>'Sweden',                     'phone_code'=>'+46',  'flag'=>'🇸🇪','postal_regex'=>'/^\d{3}\s?\d{2}$/','has_states'=>false],
        ['code'=>'CH','name'=>'Switzerland',                'phone_code'=>'+41',  'flag'=>'🇨🇭','postal_regex'=>'/^\d{4}$/','has_states'=>false],
        ['code'=>'SY','name'=>'Syria',                      'phone_code'=>'+963', 'flag'=>'🇸🇾','postal_regex'=>'','has_states'=>false],
        ['code'=>'TW','name'=>'Taiwan',                     'phone_code'=>'+886', 'flag'=>'🇹🇼','postal_regex'=>'/^\d{3}(\d{2,3})?$/','has_states'=>false],
        ['code'=>'TJ','name'=>'Tajikistan',                 'phone_code'=>'+992', 'flag'=>'🇹🇯','postal_regex'=>'/^\d{6}$/','has_states'=>false],
        ['code'=>'TZ','name'=>'Tanzania',                   'phone_code'=>'+255', 'flag'=>'🇹🇿','postal_regex'=>'/^\d{5}$/','has_states'=>false],
        ['code'=>'TH','name'=>'Thailand',                   'phone_code'=>'+66',  'flag'=>'🇹🇭','postal_regex'=>'/^\d{5}$/','has_states'=>false],
        ['code'=>'TL','name'=>'Timor-Leste',                'phone_code'=>'+670', 'flag'=>'🇹🇱','postal_regex'=>'','has_states'=>false],
        ['code'=>'TG','name'=>'Togo',                       'phone_code'=>'+228', 'flag'=>'🇹🇬','postal_regex'=>'','has_states'=>false],
        ['code'=>'TO','name'=>'Tonga',                      'phone_code'=>'+676', 'flag'=>'🇹🇴','postal_regex'=>'','has_states'=>false],
        ['code'=>'TT','name'=>'Trinidad and Tobago',        'phone_code'=>'+1',   'flag'=>'🇹🇹','postal_regex'=>'','has_states'=>false],
        ['code'=>'TN','name'=>'Tunisia',                    'phone_code'=>'+216', 'flag'=>'🇹🇳','postal_regex'=>'/^\d{4}$/','has_states'=>false],
        ['code'=>'TR','name'=>'Turkey',                     'phone_code'=>'+90',  'flag'=>'🇹🇷','postal_regex'=>'/^\d{5}$/','has_states'=>false],
        ['code'=>'TM','name'=>'Turkmenistan',               'phone_code'=>'+993', 'flag'=>'🇹🇲','postal_regex'=>'/^\d{6}$/','has_states'=>false],
        ['code'=>'TV','name'=>'Tuvalu',                     'phone_code'=>'+688', 'flag'=>'🇹🇻','postal_regex'=>'','has_states'=>false],
        ['code'=>'UG','name'=>'Uganda',                     'phone_code'=>'+256', 'flag'=>'🇺🇬','postal_regex'=>'','has_states'=>false],
        ['code'=>'UA','name'=>'Ukraine',                    'phone_code'=>'+380', 'flag'=>'🇺🇦','postal_regex'=>'/^\d{5}$/','has_states'=>false],
        ['code'=>'AE','name'=>'United Arab Emirates',       'phone_code'=>'+971', 'flag'=>'🇦🇪','postal_regex'=>'','has_states'=>false],
        ['code'=>'GB','name'=>'United Kingdom',             'phone_code'=>'+44',  'flag'=>'🇬🇧','postal_regex'=>'/^[A-Z]{1,2}\d[A-Z\d]?\s?\d[A-Z]{2}$/i','has_states'=>true],
        ['code'=>'US','name'=>'United States',              'phone_code'=>'+1',   'flag'=>'🇺🇸','postal_regex'=>'/^\d{5}(-\d{4})?$/','has_states'=>true],
        ['code'=>'UY','name'=>'Uruguay',                    'phone_code'=>'+598', 'flag'=>'🇺🇾','postal_regex'=>'/^\d{5}$/','has_states'=>false],
        ['code'=>'UZ','name'=>'Uzbekistan',                 'phone_code'=>'+998', 'flag'=>'🇺🇿','postal_regex'=>'/^\d{6}$/','has_states'=>false],
        ['code'=>'VU','name'=>'Vanuatu',                    'phone_code'=>'+678', 'flag'=>'🇻🇺','postal_regex'=>'','has_states'=>false],
        ['code'=>'VA','name'=>'Vatican City',               'phone_code'=>'+39',  'flag'=>'🇻🇦','postal_regex'=>'/^00120$/','has_states'=>false],
        ['code'=>'VE','name'=>'Venezuela',                  'phone_code'=>'+58',  'flag'=>'🇻🇪','postal_regex'=>'/^\d{4}$/','has_states'=>false],
        ['code'=>'VN','name'=>'Vietnam',                    'phone_code'=>'+84',  'flag'=>'🇻🇳','postal_regex'=>'/^\d{5,6}$/','has_states'=>false],
        ['code'=>'YE','name'=>'Yemen',                      'phone_code'=>'+967', 'flag'=>'🇾🇪','postal_regex'=>'','has_states'=>false],
        ['code'=>'ZM','name'=>'Zambia',                     'phone_code'=>'+260', 'flag'=>'🇿🇲','postal_regex'=>'/^\d{5}$/','has_states'=>false],
        ['code'=>'ZW','name'=>'Zimbabwe',                   'phone_code'=>'+263', 'flag'=>'🇿🇼','postal_regex'=>'','has_states'=>false],
    ];

    return $data;
}

/**
 * Return states/provinces indexed by country code.
 * Each state: code, name
 */
function getStatesData(): array
{
    static $data = null;
    if ($data !== null) return $data;

    $data = [

        // ── United States (50 + DC + territories) ────────────────────────
        'US' => [
            ['code'=>'AL','name'=>'Alabama'],
            ['code'=>'AK','name'=>'Alaska'],
            ['code'=>'AZ','name'=>'Arizona'],
            ['code'=>'AR','name'=>'Arkansas'],
            ['code'=>'CA','name'=>'California'],
            ['code'=>'CO','name'=>'Colorado'],
            ['code'=>'CT','name'=>'Connecticut'],
            ['code'=>'DE','name'=>'Delaware'],
            ['code'=>'DC','name'=>'District of Columbia'],
            ['code'=>'FL','name'=>'Florida'],
            ['code'=>'GA','name'=>'Georgia'],
            ['code'=>'HI','name'=>'Hawaii'],
            ['code'=>'ID','name'=>'Idaho'],
            ['code'=>'IL','name'=>'Illinois'],
            ['code'=>'IN','name'=>'Indiana'],
            ['code'=>'IA','name'=>'Iowa'],
            ['code'=>'KS','name'=>'Kansas'],
            ['code'=>'KY','name'=>'Kentucky'],
            ['code'=>'LA','name'=>'Louisiana'],
            ['code'=>'ME','name'=>'Maine'],
            ['code'=>'MD','name'=>'Maryland'],
            ['code'=>'MA','name'=>'Massachusetts'],
            ['code'=>'MI','name'=>'Michigan'],
            ['code'=>'MN','name'=>'Minnesota'],
            ['code'=>'MS','name'=>'Mississippi'],
            ['code'=>'MO','name'=>'Missouri'],
            ['code'=>'MT','name'=>'Montana'],
            ['code'=>'NE','name'=>'Nebraska'],
            ['code'=>'NV','name'=>'Nevada'],
            ['code'=>'NH','name'=>'New Hampshire'],
            ['code'=>'NJ','name'=>'New Jersey'],
            ['code'=>'NM','name'=>'New Mexico'],
            ['code'=>'NY','name'=>'New York'],
            ['code'=>'NC','name'=>'North Carolina'],
            ['code'=>'ND','name'=>'North Dakota'],
            ['code'=>'OH','name'=>'Ohio'],
            ['code'=>'OK','name'=>'Oklahoma'],
            ['code'=>'OR','name'=>'Oregon'],
            ['code'=>'PA','name'=>'Pennsylvania'],
            ['code'=>'RI','name'=>'Rhode Island'],
            ['code'=>'SC','name'=>'South Carolina'],
            ['code'=>'SD','name'=>'South Dakota'],
            ['code'=>'TN','name'=>'Tennessee'],
            ['code'=>'TX','name'=>'Texas'],
            ['code'=>'UT','name'=>'Utah'],
            ['code'=>'VT','name'=>'Vermont'],
            ['code'=>'VA','name'=>'Virginia'],
            ['code'=>'WA','name'=>'Washington'],
            ['code'=>'WV','name'=>'West Virginia'],
            ['code'=>'WI','name'=>'Wisconsin'],
            ['code'=>'WY','name'=>'Wyoming'],
            ['code'=>'AS','name'=>'American Samoa'],
            ['code'=>'GU','name'=>'Guam'],
            ['code'=>'MP','name'=>'Northern Mariana Islands'],
            ['code'=>'PR','name'=>'Puerto Rico'],
            ['code'=>'VI','name'=>'U.S. Virgin Islands'],
        ],

        // ── Canada (13 provinces/territories) ────────────────────────────
        'CA' => [
            ['code'=>'AB','name'=>'Alberta'],
            ['code'=>'BC','name'=>'British Columbia'],
            ['code'=>'MB','name'=>'Manitoba'],
            ['code'=>'NB','name'=>'New Brunswick'],
            ['code'=>'NL','name'=>'Newfoundland and Labrador'],
            ['code'=>'NT','name'=>'Northwest Territories'],
            ['code'=>'NS','name'=>'Nova Scotia'],
            ['code'=>'NU','name'=>'Nunavut'],
            ['code'=>'ON','name'=>'Ontario'],
            ['code'=>'PE','name'=>'Prince Edward Island'],
            ['code'=>'QC','name'=>'Quebec'],
            ['code'=>'SK','name'=>'Saskatchewan'],
            ['code'=>'YT','name'=>'Yukon'],
        ],

        // ── Australia (8 states/territories) ─────────────────────────────
        'AU' => [
            ['code'=>'ACT','name'=>'Australian Capital Territory'],
            ['code'=>'NSW','name'=>'New South Wales'],
            ['code'=>'NT', 'name'=>'Northern Territory'],
            ['code'=>'QLD','name'=>'Queensland'],
            ['code'=>'SA', 'name'=>'South Australia'],
            ['code'=>'TAS','name'=>'Tasmania'],
            ['code'=>'VIC','name'=>'Victoria'],
            ['code'=>'WA', 'name'=>'Western Australia'],
        ],

        // ── India (36 states + UTs) ───────────────────────────────────────
        'IN' => [
            ['code'=>'AN','name'=>'Andaman and Nicobar Islands'],
            ['code'=>'AP','name'=>'Andhra Pradesh'],
            ['code'=>'AR','name'=>'Arunachal Pradesh'],
            ['code'=>'AS','name'=>'Assam'],
            ['code'=>'BR','name'=>'Bihar'],
            ['code'=>'CH','name'=>'Chandigarh'],
            ['code'=>'CG','name'=>'Chhattisgarh'],
            ['code'=>'DN','name'=>'Dadra and Nagar Haveli and Daman and Diu'],
            ['code'=>'DL','name'=>'Delhi'],
            ['code'=>'GA','name'=>'Goa'],
            ['code'=>'GJ','name'=>'Gujarat'],
            ['code'=>'HR','name'=>'Haryana'],
            ['code'=>'HP','name'=>'Himachal Pradesh'],
            ['code'=>'JK','name'=>'Jammu and Kashmir'],
            ['code'=>'JH','name'=>'Jharkhand'],
            ['code'=>'KA','name'=>'Karnataka'],
            ['code'=>'KL','name'=>'Kerala'],
            ['code'=>'LA','name'=>'Ladakh'],
            ['code'=>'LD','name'=>'Lakshadweep'],
            ['code'=>'MP','name'=>'Madhya Pradesh'],
            ['code'=>'MH','name'=>'Maharashtra'],
            ['code'=>'MN','name'=>'Manipur'],
            ['code'=>'ML','name'=>'Meghalaya'],
            ['code'=>'MZ','name'=>'Mizoram'],
            ['code'=>'NL','name'=>'Nagaland'],
            ['code'=>'OR','name'=>'Odisha'],
            ['code'=>'PY','name'=>'Puducherry'],
            ['code'=>'PB','name'=>'Punjab'],
            ['code'=>'RJ','name'=>'Rajasthan'],
            ['code'=>'SK','name'=>'Sikkim'],
            ['code'=>'TN','name'=>'Tamil Nadu'],
            ['code'=>'TS','name'=>'Telangana'],
            ['code'=>'TR','name'=>'Tripura'],
            ['code'=>'UP','name'=>'Uttar Pradesh'],
            ['code'=>'UK','name'=>'Uttarakhand'],
            ['code'=>'WB','name'=>'West Bengal'],
        ],

        // ── United Kingdom (ceremonial regions) ──────────────────────────
        'GB' => [
            ['code'=>'ENG','name'=>'England'],
            ['code'=>'SCT','name'=>'Scotland'],
            ['code'=>'WLS','name'=>'Wales'],
            ['code'=>'NIR','name'=>'Northern Ireland'],
        ],

        // ── Bangladesh (8 divisions + 64 districts) ───────────────────────
        'BD' => [
            // Divisions
            ['code'=>'BAR','name'=>'Barisal Division'],
            ['code'=>'CHT','name'=>'Chittagong Division'],
            ['code'=>'DHK','name'=>'Dhaka Division'],
            ['code'=>'KHL','name'=>'Khulna Division'],
            ['code'=>'MYM','name'=>'Mymensingh Division'],
            ['code'=>'RAJ','name'=>'Rajshahi Division'],
            ['code'=>'RAN','name'=>'Rangpur Division'],
            ['code'=>'SYL','name'=>'Sylhet Division'],
            // Districts
            ['code'=>'BD-01','name'=>'Bandarban'],
            ['code'=>'BD-02','name'=>'Barguna'],
            ['code'=>'BD-03','name'=>'Barishal'],
            ['code'=>'BD-04','name'=>'Bhola'],
            ['code'=>'BD-05','name'=>'Bogura'],
            ['code'=>'BD-06','name'=>'Brahmanbaria'],
            ['code'=>'BD-07','name'=>'Chandpur'],
            ['code'=>'BD-08','name'=>'Chattogram'],
            ['code'=>'BD-09','name'=>'Chuadanga'],
            ['code'=>'BD-10','name'=>'Cox\'s Bazar'],
            ['code'=>'BD-11','name'=>'Cumilla'],
            ['code'=>'BD-12','name'=>'Dhaka'],
            ['code'=>'BD-13','name'=>'Dinajpur'],
            ['code'=>'BD-14','name'=>'Faridpur'],
            ['code'=>'BD-15','name'=>'Feni'],
            ['code'=>'BD-16','name'=>'Gaibandha'],
            ['code'=>'BD-17','name'=>'Gazipur'],
            ['code'=>'BD-18','name'=>'Gopalganj'],
            ['code'=>'BD-19','name'=>'Habiganj'],
            ['code'=>'BD-20','name'=>'Jamalpur'],
            ['code'=>'BD-21','name'=>'Jashore'],
            ['code'=>'BD-22','name'=>'Jhalokathi'],
            ['code'=>'BD-23','name'=>'Jhenaidah'],
            ['code'=>'BD-24','name'=>'Joypurhat'],
            ['code'=>'BD-25','name'=>'Khagrachhari'],
            ['code'=>'BD-26','name'=>'Khulna'],
            ['code'=>'BD-27','name'=>'Kishoreganj'],
            ['code'=>'BD-28','name'=>'Kurigram'],
            ['code'=>'BD-29','name'=>'Kushtia'],
            ['code'=>'BD-30','name'=>'Lakshmipur'],
            ['code'=>'BD-31','name'=>'Lalmonirhat'],
            ['code'=>'BD-32','name'=>'Madaripur'],
            ['code'=>'BD-33','name'=>'Magura'],
            ['code'=>'BD-34','name'=>'Manikganj'],
            ['code'=>'BD-35','name'=>'Meherpur'],
            ['code'=>'BD-36','name'=>'Moulvibazar'],
            ['code'=>'BD-37','name'=>'Munshiganj'],
            ['code'=>'BD-38','name'=>'Mymensingh'],
            ['code'=>'BD-39','name'=>'Naogaon'],
            ['code'=>'BD-40','name'=>'Narail'],
            ['code'=>'BD-41','name'=>'Narayanganj'],
            ['code'=>'BD-42','name'=>'Narsingdi'],
            ['code'=>'BD-43','name'=>'Natore'],
            ['code'=>'BD-44','name'=>'Nawabganj'],
            ['code'=>'BD-45','name'=>'Netrokona'],
            ['code'=>'BD-46','name'=>'Nilphamari'],
            ['code'=>'BD-47','name'=>'Noakhali'],
            ['code'=>'BD-48','name'=>'Pabna'],
            ['code'=>'BD-49','name'=>'Panchagarh'],
            ['code'=>'BD-50','name'=>'Patuakhali'],
            ['code'=>'BD-51','name'=>'Pirojpur'],
            ['code'=>'BD-52','name'=>'Rajbari'],
            ['code'=>'BD-53','name'=>'Rajshahi'],
            ['code'=>'BD-54','name'=>'Rangamati'],
            ['code'=>'BD-55','name'=>'Rangpur'],
            ['code'=>'BD-56','name'=>'Satkhira'],
            ['code'=>'BD-57','name'=>'Shariatpur'],
            ['code'=>'BD-58','name'=>'Sherpur'],
            ['code'=>'BD-59','name'=>'Sirajganj'],
            ['code'=>'BD-60','name'=>'Sunamganj'],
            ['code'=>'BD-61','name'=>'Sylhet'],
            ['code'=>'BD-62','name'=>'Tangail'],
            ['code'=>'BD-63','name'=>'Thakurgaon'],
        ],

        // ── Germany (16 states) ───────────────────────────────────────────
        'DE' => [
            ['code'=>'BB','name'=>'Brandenburg'],
            ['code'=>'BE','name'=>'Berlin'],
            ['code'=>'BW','name'=>'Baden-Württemberg'],
            ['code'=>'BY','name'=>'Bavaria'],
            ['code'=>'HB','name'=>'Bremen'],
            ['code'=>'HE','name'=>'Hesse'],
            ['code'=>'HH','name'=>'Hamburg'],
            ['code'=>'MV','name'=>'Mecklenburg-Vorpommern'],
            ['code'=>'NI','name'=>'Lower Saxony'],
            ['code'=>'NW','name'=>'North Rhine-Westphalia'],
            ['code'=>'RP','name'=>'Rhineland-Palatinate'],
            ['code'=>'SH','name'=>'Schleswig-Holstein'],
            ['code'=>'SL','name'=>'Saarland'],
            ['code'=>'SN','name'=>'Saxony'],
            ['code'=>'ST','name'=>'Saxony-Anhalt'],
            ['code'=>'TH','name'=>'Thuringia'],
        ],

        // ── France (13 metropolitan regions) ─────────────────────────────
        'FR' => [
            ['code'=>'ARA','name'=>'Auvergne-Rhône-Alpes'],
            ['code'=>'BFC','name'=>'Bourgogne-Franche-Comté'],
            ['code'=>'BRE','name'=>'Brittany'],
            ['code'=>'CVL','name'=>'Centre-Val de Loire'],
            ['code'=>'COR','name'=>'Corsica'],
            ['code'=>'GES','name'=>'Grand Est'],
            ['code'=>'HDF','name'=>'Hauts-de-France'],
            ['code'=>'IDF','name'=>'Île-de-France'],
            ['code'=>'NOR','name'=>'Normandy'],
            ['code'=>'NAQ','name'=>'Nouvelle-Aquitaine'],
            ['code'=>'OCC','name'=>'Occitanie'],
            ['code'=>'PDL','name'=>'Pays de la Loire'],
            ['code'=>'PAC','name'=>'Provence-Alpes-Côte d\'Azur'],
        ],

        // ── China (34 provinces/municipalities/autonomous regions/SARs) ───
        'CN' => [
            ['code'=>'AH','name'=>'Anhui'],
            ['code'=>'BJ','name'=>'Beijing'],
            ['code'=>'CQ','name'=>'Chongqing'],
            ['code'=>'FJ','name'=>'Fujian'],
            ['code'=>'GS','name'=>'Gansu'],
            ['code'=>'GD','name'=>'Guangdong'],
            ['code'=>'GX','name'=>'Guangxi'],
            ['code'=>'GZ','name'=>'Guizhou'],
            ['code'=>'HI','name'=>'Hainan'],
            ['code'=>'HE','name'=>'Hebei'],
            ['code'=>'HL','name'=>'Heilongjiang'],
            ['code'=>'HA','name'=>'Henan'],
            ['code'=>'HK','name'=>'Hong Kong SAR'],
            ['code'=>'HB','name'=>'Hubei'],
            ['code'=>'HN','name'=>'Hunan'],
            ['code'=>'JS','name'=>'Jiangsu'],
            ['code'=>'JX','name'=>'Jiangxi'],
            ['code'=>'JL','name'=>'Jilin'],
            ['code'=>'LN','name'=>'Liaoning'],
            ['code'=>'MO','name'=>'Macao SAR'],
            ['code'=>'NM','name'=>'Inner Mongolia'],
            ['code'=>'NX','name'=>'Ningxia'],
            ['code'=>'QH','name'=>'Qinghai'],
            ['code'=>'SN','name'=>'Shaanxi'],
            ['code'=>'SD','name'=>'Shandong'],
            ['code'=>'SH','name'=>'Shanghai'],
            ['code'=>'SX','name'=>'Shanxi'],
            ['code'=>'SC','name'=>'Sichuan'],
            ['code'=>'TJ','name'=>'Tianjin'],
            ['code'=>'XJ','name'=>'Xinjiang'],
            ['code'=>'XZ','name'=>'Tibet'],
            ['code'=>'YN','name'=>'Yunnan'],
            ['code'=>'ZJ','name'=>'Zhejiang'],
        ],

        // ── Japan (47 prefectures) ────────────────────────────────────────
        'JP' => [
            ['code'=>'JP-01','name'=>'Hokkaido'],
            ['code'=>'JP-02','name'=>'Aomori'],
            ['code'=>'JP-03','name'=>'Iwate'],
            ['code'=>'JP-04','name'=>'Miyagi'],
            ['code'=>'JP-05','name'=>'Akita'],
            ['code'=>'JP-06','name'=>'Yamagata'],
            ['code'=>'JP-07','name'=>'Fukushima'],
            ['code'=>'JP-08','name'=>'Ibaraki'],
            ['code'=>'JP-09','name'=>'Tochigi'],
            ['code'=>'JP-10','name'=>'Gunma'],
            ['code'=>'JP-11','name'=>'Saitama'],
            ['code'=>'JP-12','name'=>'Chiba'],
            ['code'=>'JP-13','name'=>'Tokyo'],
            ['code'=>'JP-14','name'=>'Kanagawa'],
            ['code'=>'JP-15','name'=>'Niigata'],
            ['code'=>'JP-16','name'=>'Toyama'],
            ['code'=>'JP-17','name'=>'Ishikawa'],
            ['code'=>'JP-18','name'=>'Fukui'],
            ['code'=>'JP-19','name'=>'Yamanashi'],
            ['code'=>'JP-20','name'=>'Nagano'],
            ['code'=>'JP-21','name'=>'Gifu'],
            ['code'=>'JP-22','name'=>'Shizuoka'],
            ['code'=>'JP-23','name'=>'Aichi'],
            ['code'=>'JP-24','name'=>'Mie'],
            ['code'=>'JP-25','name'=>'Shiga'],
            ['code'=>'JP-26','name'=>'Kyoto'],
            ['code'=>'JP-27','name'=>'Osaka'],
            ['code'=>'JP-28','name'=>'Hyogo'],
            ['code'=>'JP-29','name'=>'Nara'],
            ['code'=>'JP-30','name'=>'Wakayama'],
            ['code'=>'JP-31','name'=>'Tottori'],
            ['code'=>'JP-32','name'=>'Shimane'],
            ['code'=>'JP-33','name'=>'Okayama'],
            ['code'=>'JP-34','name'=>'Hiroshima'],
            ['code'=>'JP-35','name'=>'Yamaguchi'],
            ['code'=>'JP-36','name'=>'Tokushima'],
            ['code'=>'JP-37','name'=>'Kagawa'],
            ['code'=>'JP-38','name'=>'Ehime'],
            ['code'=>'JP-39','name'=>'Kochi'],
            ['code'=>'JP-40','name'=>'Fukuoka'],
            ['code'=>'JP-41','name'=>'Saga'],
            ['code'=>'JP-42','name'=>'Nagasaki'],
            ['code'=>'JP-43','name'=>'Kumamoto'],
            ['code'=>'JP-44','name'=>'Oita'],
            ['code'=>'JP-45','name'=>'Miyazaki'],
            ['code'=>'JP-46','name'=>'Kagoshima'],
            ['code'=>'JP-47','name'=>'Okinawa'],
        ],
    ];

    return $data;
}

/**
 * Basic postal code lookup data for US, UK, CA.
 * Returns ['city', 'state_code', 'state_name'] or empty array.
 */
function getPostalLookupData(): array
{
    static $lookup = null;
    if ($lookup !== null) return $lookup;

    $lookup = [
        'US' => [
            '10001' => ['city' => 'New York',       'state_code' => 'NY', 'state_name' => 'New York'],
            '10002' => ['city' => 'New York',       'state_code' => 'NY', 'state_name' => 'New York'],
            '90001' => ['city' => 'Los Angeles',    'state_code' => 'CA', 'state_name' => 'California'],
            '90210' => ['city' => 'Beverly Hills',  'state_code' => 'CA', 'state_name' => 'California'],
            '60601' => ['city' => 'Chicago',        'state_code' => 'IL', 'state_name' => 'Illinois'],
            '77001' => ['city' => 'Houston',        'state_code' => 'TX', 'state_name' => 'Texas'],
            '85001' => ['city' => 'Phoenix',        'state_code' => 'AZ', 'state_name' => 'Arizona'],
            '19101' => ['city' => 'Philadelphia',   'state_code' => 'PA', 'state_name' => 'Pennsylvania'],
            '78201' => ['city' => 'San Antonio',    'state_code' => 'TX', 'state_name' => 'Texas'],
            '92101' => ['city' => 'San Diego',      'state_code' => 'CA', 'state_name' => 'California'],
            '75201' => ['city' => 'Dallas',         'state_code' => 'TX', 'state_name' => 'Texas'],
            '95101' => ['city' => 'San Jose',       'state_code' => 'CA', 'state_name' => 'California'],
            '78701' => ['city' => 'Austin',         'state_code' => 'TX', 'state_name' => 'Texas'],
            '30301' => ['city' => 'Atlanta',        'state_code' => 'GA', 'state_name' => 'Georgia'],
            '98101' => ['city' => 'Seattle',        'state_code' => 'WA', 'state_name' => 'Washington'],
            '02101' => ['city' => 'Boston',         'state_code' => 'MA', 'state_name' => 'Massachusetts'],
            '80201' => ['city' => 'Denver',         'state_code' => 'CO', 'state_name' => 'Colorado'],
            '97201' => ['city' => 'Portland',       'state_code' => 'OR', 'state_name' => 'Oregon'],
            '89101' => ['city' => 'Las Vegas',      'state_code' => 'NV', 'state_name' => 'Nevada'],
            '33101' => ['city' => 'Miami',          'state_code' => 'FL', 'state_name' => 'Florida'],
            '20001' => ['city' => 'Washington',     'state_code' => 'DC', 'state_name' => 'District of Columbia'],
        ],
        'CA' => [
            'M5A 1A1' => ['city' => 'Toronto',       'state_code' => 'ON', 'state_name' => 'Ontario'],
            'V6B 1A1' => ['city' => 'Vancouver',     'state_code' => 'BC', 'state_name' => 'British Columbia'],
            'H1A 0A1' => ['city' => 'Montreal',      'state_code' => 'QC', 'state_name' => 'Quebec'],
            'T2P 1A1' => ['city' => 'Calgary',       'state_code' => 'AB', 'state_name' => 'Alberta'],
            'T5A 0A1' => ['city' => 'Edmonton',      'state_code' => 'AB', 'state_name' => 'Alberta'],
            'K1A 0A1' => ['city' => 'Ottawa',        'state_code' => 'ON', 'state_name' => 'Ontario'],
        ],
        'GB' => [
            'SW1A 1AA' => ['city' => 'London',      'state_code' => 'ENG', 'state_name' => 'England'],
            'M1 1AE'   => ['city' => 'Manchester',  'state_code' => 'ENG', 'state_name' => 'England'],
            'EH1 1AA'  => ['city' => 'Edinburgh',   'state_code' => 'SCT', 'state_name' => 'Scotland'],
            'CF10 1AA' => ['city' => 'Cardiff',     'state_code' => 'WLS', 'state_name' => 'Wales'],
            'BT1 1AA'  => ['city' => 'Belfast',     'state_code' => 'NIR', 'state_name' => 'Northern Ireland'],
            'B1 1AA'   => ['city' => 'Birmingham',  'state_code' => 'ENG', 'state_name' => 'England'],
            'LS1 1AA'  => ['city' => 'Leeds',       'state_code' => 'ENG', 'state_name' => 'England'],
        ],
    ];

    return $lookup;
}

/**
 * City suggestions by country (basic built-in data).
 */
function getCitySuggestionsData(): array
{
    static $data = null;
    if ($data !== null) return $data;

    $data = [
        'US' => ['New York','Los Angeles','Chicago','Houston','Phoenix','Philadelphia','San Antonio','San Diego','Dallas','San Jose','Austin','Jacksonville','Fort Worth','Columbus','Charlotte','Indianapolis','San Francisco','Seattle','Denver','Nashville','Oklahoma City','El Paso','Washington','Boston','Las Vegas','Memphis','Louisville','Portland','Baltimore','Milwaukee'],
        'CA' => ['Toronto','Montreal','Vancouver','Calgary','Edmonton','Ottawa','Winnipeg','Quebec City','Hamilton','Kitchener','London','Victoria','Halifax','Oshawa','Windsor','Saskatoon','Regina','St. Catharines','Kelowna','Barrie','Abbotsford','Sherbrooke','Sudbury','Saguenay','Trois-Rivières'],
        'AU' => ['Sydney','Melbourne','Brisbane','Perth','Adelaide','Gold Coast','Newcastle','Canberra','Sunshine Coast','Wollongong','Logan','Geelong','Hobart','Townsville','Cairns','Darwin','Toowoomba','Ballarat','Bendigo','Albury','Launceston','Mackay','Rockhampton'],
        'IN' => ['Mumbai','Delhi','Bangalore','Hyderabad','Ahmedabad','Chennai','Kolkata','Surat','Pune','Jaipur','Lucknow','Kanpur','Nagpur','Visakhapatnam','Indore','Thane','Bhopal','Pimpri-Chinchwad','Patna','Vadodara','Ghaziabad','Ludhiana','Agra','Nashik','Faridabad','Meerut','Rajkot','Varanasi','Srinagar','Aurangabad','Dhanbad','Amritsar','Navi Mumbai','Allahabad','Ranchi','Howrah','Coimbatore','Jabalpur','Gwalior','Vijayawada'],
        'GB' => ['London','Birmingham','Manchester','Glasgow','Liverpool','Leeds','Sheffield','Edinburgh','Bristol','Leicester','Coventry','Cardiff','Bradford','Nottingham','Kingston upon Hull','Belfast','Southampton','Aberdeen','Newcastle upon Tyne','Stoke-on-Trent','Wolverhampton','Plymouth','Derby','Swansea','Middlesbrough'],
        'BD' => ['Dhaka','Chittagong','Rajshahi','Khulna','Sylhet','Barishal','Rangpur','Mymensingh','Comilla','Narayanganj','Gazipur','Tongi','Jessore','Bogura','Dinajpur','Nawabganj','Saidpur','Jamalpur','Tangail','Sirajganj','Feni','Cox\'s Bazar','Brahmanbaria','Manikganj','Pabna'],
        'DE' => ['Berlin','Hamburg','Munich','Cologne','Frankfurt','Stuttgart','Düsseldorf','Leipzig','Dortmund','Essen','Bremen','Dresden','Hanover','Nuremberg','Duisburg','Bochum','Wuppertal','Bielefeld','Bonn','Münster'],
        'FR' => ['Paris','Marseille','Lyon','Toulouse','Nice','Nantes','Strasbourg','Montpellier','Bordeaux','Lille','Rennes','Reims','Le Havre','Saint-Étienne','Toulon','Grenoble','Dijon','Angers','Nîmes','Villeurbanne'],
        'CN' => ['Beijing','Shanghai','Guangzhou','Shenzhen','Chengdu','Chongqing','Tianjin','Wuhan','Xi\'an','Hangzhou','Nanjing','Dongguan','Shenyang','Qingdao','Jinan','Changsha','Kunming','Harbin','Zhengzhou','Dalian'],
        'JP' => ['Tokyo','Yokohama','Osaka','Nagoya','Sapporo','Fukuoka','Kawasaki','Kobe','Kyoto','Saitama','Hiroshima','Sendai','Chiba','Kitakyushu','Sakai','Niigata','Hamamatsu','Shizuoka','Sagamihara','Okayama'],
    ];

    return $data;
}
